cloud_name: "dhzyzerqn"
cloudinary_api_key: '423992294897841'
cloudinary_secret: 0aVoAIUa1SwMQNw5n3RdtbY2DJM
CLOUDINARY_URL: cloudinary://423992294897841:0aVoAIUa1SwMQNw5n3RdtbY2DJM@dhzyzerqn
TWITTER_CONSUMER_KEY: wJG02yiuXBOOC8sAWmrd2PHMU
TWITTER_CONSUMER_API_SECRET: tZARk3xknUxTjw4syqTBVYPdl6RzQZgwMYg0qeu3VKGJEu2lmm
store_twitter_token: 962795945267290112-FVvtpSuaMesmJ0vzKGHHjDIAnjQ1Lng
store_twitter_secret: 8Prnp4C3Wu6eepWx6hsLjH0woChdWLQF4FFDkMHQdq3xm
