production: &production
  adapter: redis
  url: redis://redistogo:f8bbd7d62a25adbadea9c8fcdddfad46@soldierfish.redistogo.com:11124/
development: &development
  adapter: redis
  url: redis://localhost:6379/1
test: *development
